baseURL = "https://comingsoon-landpage.netlify.app/"
languageCode = "en-us"
title = "Shielaj | Comming Soon"
theme = "infinity-hugo"
removePathAccents = true


# HTML before the closing </head>
[params]
customHead = ""

# Navigation
[params.navigation]
logo = "images/logo.png"
home = "Home"
about = "About"
service = "Services"
contact = "Contact"

# Hero Area
[params.hero]
enable = true
bg = "images/header-bg.jpg"
title = "ZOOM IN ON THE FUTURE OF SCIENCE"
subtitle = "Get ready to embark on a journey that will change the way you see the world. Our cutting-edge microscope is about to unlock a realm of incredible discoveries, where the tiniest details hold the biggest secrets. With precision optics and groundbreaking technology, our microscope is set to redefine scientific exploration. Stay tuned as we prepare to unveil the future of science. The countdown has begun â€“ the microscope revolution is coming soon."
btnText = "Get Started"

# counter
disableCountdown = false
countdownYear = "2023"
countdownMonth = "12"
countdownDay = "25"

# About Section
[params.about]
enable = true
heading = "Our mission is to empower scientists, researchers, educators, and curious minds to delve deeper into the mysteries of the universe."
description = "With the 'Zoom In on the Future of Science' microscope, we're not just providing a scientific instrument; we're enabling a new era of discovery. Join us on this exciting journey as we prepare to unveil a product that will change the course of scientific exploration. Stay connected, stay curious, and get ready to embrace the future of science.<br><br>The microscope of tomorrow is almost here. Are you ready to zoom in and witness the revolution?"

[[params.about.sliderItem]]
image = "images/about/1.jpg"
[[params.about.sliderItem]]
image = "images/about/2.jpg"
[[params.about.sliderItem]]
image = "images/about/3.jpg"
[[params.about.sliderItem]]
image = "images/about/2.jpg"


# Service Section
[params.service]
enable = true
title = " Explore the Invisible with Our Microscope"
subtitle = "These services are crucial for ensuring the successful use and longevity of microscope products in various scientific and research applications."


[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon = "tf-document3"
title = "Product Training"
description = "Offering training sessions to users on how to properly operate and maintain the microscope, ensuring optimal performance and longevity."
delay = "0s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon = "tf-gears"
title = "Calibration and Maintenance"
description = "Providing regular calibration and maintenance services to keep the microscope functioning at its best."
delay = "0.2s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon = "tf-tools"
title = "Technical Support"
description = "Offering technical support and assistance for troubleshooting issues and answering user queries."
delay = "0.4s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon = "tf-linegraph"
title = "Image Analysis"
description = "Providing software solutions for image capture, processing, and analysis, enhancing the capabilities of the microscope."
delay = "0.6s"



# Call to Action Section
[params.cta]
enable = true
bg = "images/call-to-action.jpg"
title = "Subscribe to our mailing list"
subtitle = "Subscribe today to be among the first to witness the groundbreaking innovation in microscopy. Get ready to explore the unseen, dive into the microscopic world, and revolutionize your research."

[params.contact]
enable = true
title = "Get In Touch with Us for Microscope Excellence!"
description = "We're here to answer your questions, address your needs, and provide the information you're looking for. Whether you're a researcher, scientist, educator, or enthusiast, we're eager to assist you on your journey to explore the microscopic world. Feel free to reach out with any inquiries, requests, or collaboration opportunities. We value your curiosity and are excited to be part of your scientific endeavors. Let's connect and embark on this exciting scientific voyage together. Contact us today!"
